name: Loopstats.LoopStats-CD

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Loopstats.LoopStats-CI"]
    branches: 
      - 'master'
    types: [completed]

env:
  ARTIFACT_NAME: Loopstats.LoopStats-CI
  WORKFLOW_NAME: ci-loopstats-function.yml

jobs:
  deploy-to-prod:
    name: Publish App to Prod
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.PROJECT_DIRECTORY }}
    environment: prod
    env:
      RESOURCE_GROUP_NAME: LoopyStatsRG
      FUNCTION_APP_NAME: LoopyStats
      BASE_URL: 'https://loopystats.azurewebsites.net'
    steps:
      - uses: actions/checkout@v2

      # Using a marketplace task until sharing of artifacts between workflows is implemented
      - name: Download Build Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ env.WORKFLOW_NAME }}
          workflow_conclusion: success
          name: ${{ env.ARTIFACT_NAME }}.zip
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Azure Function
        uses: azure/functions-action@v1
        with:
          app-name: ${{ env.FUNCTION_APP_NAME }}
          package: ${{ env.ARTIFACT_NAME }}.zip
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
